job('Firest-Maven-Project-Via_DSL'){
	description("First Maven job generated by the DSL on ${new Date()}, the project is a small Maven project hosted on github")
	scm{
	   git("git@github.com:satish2786/Hello-world-Java-Project", master)
	}
	triggers {
		scm('* * * * *')
	}
	steps {
		maven('clean pakage', 'Hello-world-Java-Project/pom.xml')
	}
	publishers {
		//archive the war file generated
		archiveArtifacrts '**/*.jar'
	}
}
